version: '2'
services:
    hbinsserverregistry-app:
        image: hbinsserverregistry
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hbinsserverregistry-mysql:3306/hbinsserverregistry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8001:8001
    hbinsserverregistry-mysql:
        extends:
            file: mysql.yml
            service: hbinsserverregistry-mysql
